# fly.toml app configuration file generated for cikwo on 2023-06-16T22:39:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cikwo"
primary_region = "sin"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
